"""The production half of the logical-source indirection: DDL for `<target_db>.MIG_SRC_<WF>`.

    python scripts/gen_source_views.py <wf_id> [--root .] [--out PATH]

A translated procedure builds each source's name as
`LET <LOGICAL>_SRC VARCHAR := SRC_DB || '.' || SRC_SCHEMA || '.<LOGICAL>';`, reads it as
`IDENTIFIER(:<LOGICAL>_SRC)` (contract C4's documented form) and never names a production
schema. Tests point `SRC_SCHEMA` at the golden view schema `load_golden.py` builds; production
points it at the schema this script's DDL creates, whose views map the same logical names to the
real tables confirmed during intake. One procedure body, two worlds.

Final targets need no view: procedures write through `TGT_DB`/`TGT_SCHEMA` to the logical name,
and Snowflake cannot insert through a view anyway.

The DDL is generated text. It has not been executed against a Snowflake account in this repo.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from lib.io import read_yaml
from lib.paths import Repo, add_root_arg, wf_token


def source_view_schema(wf_id: str) -> str:
    return f"MIG_SRC_{wf_token(wf_id)}"


def production_views_sql(wf_id: str, mappings: dict, program: dict) -> str:
    """`intake/mappings.yaml` + the program block → CREATE SCHEMA/VIEW text, ordered by name."""
    database = program.get("target_database")
    if not database:
        raise ValueError("mappings/global.yaml program block has no `target_database`")
    schema = f"{database}.{source_view_schema(wf_id)}"

    views = []
    for key, source in (mappings.get("sources") or {}).items():
        tool_ids = [str(tool_id) for tool_id in source.get("tool_ids") or []]
        logical = source.get("logical")
        if not logical:
            where = f"tool {', '.join(tool_ids)}" if tool_ids else "no tool id recorded"
            raise ValueError(f"source {key!r} ({where}) has no `logical:` name in "
                             f"intake/mappings.yaml (plan contract C6)")
        table = source.get("snowflake")
        if not table:
            raise ValueError(f"source {key!r} has no confirmed `snowflake:` table")
        views.append((str(logical), str(table), key))

    lines = [
        f"-- Source views for {wf_id}: the logical names its procedures read, mapped to the tables",
        "-- confirmed during intake. Generated by scripts/gen_source_views.py; never executed",
        "-- against a Snowflake account in this repository.",
        f"CREATE SCHEMA IF NOT EXISTS {schema};",
    ]
    for logical, table, key in sorted(views):
        lines.append(f"-- {key}")
        lines.append(f"CREATE OR REPLACE VIEW {schema}.{logical} AS SELECT * FROM {table};")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("wf_id", help="workflow id, e.g. wf_0003")
    parser.add_argument("--out", help="write the DDL here instead of stdout")
    add_root_arg(parser)
    args = parser.parse_args(argv)

    repo = Repo(args.root)
    # Usage problems are settled before anything is written.
    mappings_path = repo.wf(args.wf_id, "intake", "mappings.yaml")
    for path, what in ((mappings_path, f"{args.wf_id} has no intake/mappings.yaml"),
                       (repo.global_mappings, "there are no program answers")):
        if not path.exists():
            parser.error(f"{what}, so no source views can be generated: {path}")

    try:
        sql = production_views_sql(args.wf_id, read_yaml(mappings_path) or {},
                                   (read_yaml(repo.global_mappings) or {}).get("program") or {})
    except ValueError as exc:       # domain failure: intake has not answered enough yet
        print(f"{args.wf_id}: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"{args.wf_id}: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 2

    if not args.out:
        sys.stdout.write(sql)
        return 0
    try:
        path = Path(args.out)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(sql)
    except OSError as exc:
        print(f"{args.wf_id}: cannot write {args.out}: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    from lib.console import utf8_console
    utf8_console()
    sys.exit(main())
